export const CURRENT_ENV = {
  API_URL: process.env.REACT_APP_BASE_URL_SERVICE,
  SECRET_KEY: process.env.REACT_APP_SECRET_KEY,
  CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
  LOGIN_LOGO: process.env.REACT_APP_LOGIN_LOGO,
  HEADER_LOGO: process.env.REACT_APP_HEADER_LOGO,
  BASE_URL_LOCATION: process.env.REACT_APP_BASE_URL_LOCATION
};
